"""The TUI's only theme, built from the shared palette; there is no light mode."""

from textual.theme import Theme

from protostar.cli.palette import (
    AMBER,
    CONSOLE,
    CYAN,
    DECK,
    DIM,
    FAINT,
    GLOW,
    GREEN,
    HAIRLINE,
    INK,
    RED,
    SOFT,
    STRUT,
    TEXT,
)

PROTOSTAR = Theme(
    name="protostar",
    primary=CYAN,
    secondary=CYAN,
    accent=CYAN,
    warning=AMBER,
    error=RED,
    success=GREEN,
    foreground=TEXT,
    background=INK,
    surface=DECK,
    panel=CONSOLE,
    dark=True,
    variables={
        "hairline": HAIRLINE,
        "strut": STRUT,
        "glow": GLOW,
        "text-muted": SOFT,
        "text-faint": FAINT,
        "text-disabled": DIM,
        "text-success": GREEN,
        "text-warning": AMBER,
        "text-error": RED,
        "border": CYAN,
        "border-blurred": HAIRLINE,
        "block-cursor-background": GLOW,
        "block-cursor-foreground": CYAN,
        "block-cursor-text-style": "bold",
        "block-cursor-blurred-background": CONSOLE,
        "block-cursor-blurred-foreground": TEXT,
        "block-cursor-blurred-text-style": "none",
        "block-hover-background": CONSOLE,
        "input-cursor-background": CYAN,
        "input-cursor-foreground": INK,
        "input-selection-background": f"{CYAN} 25%",
        "scrollbar": STRUT,
        "scrollbar-hover": FAINT,
        "scrollbar-active": CYAN,
        "scrollbar-background": DECK,
        "scrollbar-background-hover": DECK,
        "scrollbar-background-active": DECK,
        "scrollbar-corner-color": DECK,
        "footer-background": CONSOLE,
        "footer-foreground": SOFT,
        "footer-key-foreground": CYAN,
        "footer-key-background": CONSOLE,
        "footer-description-foreground": SOFT,
        "footer-description-background": CONSOLE,
        "footer-item-background": CONSOLE,
        "button-foreground": TEXT,
        "button-color-foreground": INK,
        "button-focus-text-style": "bold",
    },
)
"""The app's only theme."""
