"""Planning and applying the git hooks ``sync`` keeps in line with the recipe."""

from pathlib import Path

import pytest

from protostar.config import UserConfig
from protostar.errors import CommandExecutionError
from protostar.executor import SystemExecutor
from protostar.git_hooks import (
    NO_HOOK_ACTION,
    HookAction,
    configurations,
    generator,
    install_task,
    plan_hooks,
)
from protostar.manifest import EnvironmentManifest, Severity, ToolingManifest
from protostar.workflows import HookRunner

PREK_HOOK = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n"
PRE_COMMIT_HOOK = (
    "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n"
)


def tooling(runner=HookRunner.NONE, *types):
    result = ToolingManifest()
    if runner is not HookRunner.NONE:
        result.set_hook_runner(runner)
    for kind in types:
        result.add_pre_commit_hook_type(kind)
    return result


@pytest.fixture
def hooks(tmp_path):
    directory = tmp_path / ".git" / "hooks"
    directory.mkdir(parents=True)
    (directory / "pre-commit.sample").write_text("#!/bin/sh\n")
    return directory


def test_generator_reads_the_marker_of_either_runner(hooks):
    (hooks / "pre-commit").write_text(PREK_HOOK)
    (hooks / "pre-push").write_text(PRE_COMMIT_HOOK)
    (hooks / "commit-msg").write_text("#!/bin/sh\nexit 0\n")
    assert generator(hooks / "pre-commit") is HookRunner.PREK
    assert generator(hooks / "pre-push") is HookRunner.PRE_COMMIT
    assert generator(hooks / "commit-msg") is None
    assert generator(hooks / "missing") is None


def test_nothing_is_planned_outside_a_plain_git_repository(tmp_path):
    assert plan_hooks(tmp_path, tooling(HookRunner.PREK), ()) is NO_HOOK_ACTION
    (tmp_path / ".git").write_text("gitdir: ../elsewhere\n")
    assert plan_hooks(tmp_path, tooling(HookRunner.PREK), ()) is NO_HOOK_ACTION


def test_a_missing_wanted_hook_installs_them_all(tmp_path, hooks):
    (hooks / "pre-commit").write_text(PREK_HOOK)
    action = plan_hooks(tmp_path, tooling(HookRunner.PREK, "commit-msg"), ())
    assert action.install is not None
    assert action.install.command == ["uv", "run", "prek", "install"]
    assert action.install.owned_files == [
        ".git/hooks/commit-msg",
        ".git/hooks/pre-commit",
    ]
    assert action.remove == ()


def test_installed_hooks_need_nothing(tmp_path, hooks):
    (hooks / "pre-commit").write_text(PREK_HOOK)
    (hooks / "commit-msg").write_text(PREK_HOOK)
    # A type the runner installed on the user's request keeps working.
    (hooks / "post-checkout").write_text(PREK_HOOK)
    action = plan_hooks(tmp_path, tooling(HookRunner.PREK, "commit-msg"), ())
    assert action == HookAction()
    assert not action.pending


def test_a_hand_written_hook_is_never_removed_but_is_installed_over(tmp_path, hooks):
    (hooks / "pre-commit").write_text("#!/bin/sh\n./my-checks\n")
    assert plan_hooks(tmp_path, tooling(), ()) == HookAction()
    action = plan_hooks(tmp_path, tooling(HookRunner.PREK), ())
    assert action.install is not None
    assert action.remove == ()


def test_switching_runner_removes_the_old_runners_hooks(tmp_path, hooks):
    (hooks / "pre-commit").write_text(PRE_COMMIT_HOOK)
    (hooks / "pre-push").write_text(PRE_COMMIT_HOOK)
    action = plan_hooks(tmp_path, tooling(HookRunner.PREK), [".pre-commit-config.yaml"])
    assert action.remove == (".git/hooks/pre-commit", ".git/hooks/pre-push")
    assert action.install is not None


def test_without_a_runner_generated_hooks_go_with_their_configuration(tmp_path, hooks):
    (hooks / "pre-commit").write_text(PREK_HOOK)
    assert plan_hooks(tmp_path, tooling(), ()).remove == (".git/hooks/pre-commit",)
    # A configuration the user keeps still runs, so its hooks stay.
    for name in configurations():
        assert plan_hooks(tmp_path, tooling(), [name]) == HookAction()


def test_the_install_names_its_runner():
    task = install_task(tooling(HookRunner.PRE_COMMIT, "pre-push"))
    assert task.command == ["uv", "run", "pre-commit", "install"]
    assert task.description == "Installing pre-commit git hooks"
    assert task.timeout == 600


def executor(tmp_path, monkeypatch, mocker):
    monkeypatch.chdir(tmp_path)
    result = SystemExecutor(EnvironmentManifest(), UserConfig())
    run = mocker.patch.object(result.process_runner, "run")
    return result, run


def test_applying_removes_hooks_and_runs_the_install(
    tmp_path, hooks, monkeypatch, mocker
):
    (hooks / "pre-push").write_text(PRE_COMMIT_HOOK)
    engine, run = executor(tmp_path, monkeypatch, mocker)
    task = install_task(tooling(HookRunner.PREK))
    engine._apply_hooks(HookAction(task, (".git/hooks/pre-push",)))
    assert not (hooks / "pre-push").exists()
    run.assert_called_once_with(["uv", "run", "prek", "install"], timeout=600)
    assert engine.completed_tasks == [task]
    engine.journal.rollback()
    assert (hooks / "pre-push").read_text() == PRE_COMMIT_HOOK


def test_a_failed_install_is_a_warning_not_a_rollback(
    tmp_path, hooks, monkeypatch, mocker
):
    engine, run = executor(tmp_path, monkeypatch, mocker)
    run.side_effect = CommandExecutionError(
        ["uv", "run", "prek", "install"], 1, stderr="core.hooksPath is set"
    )
    engine._apply_hooks(HookAction(install_task(tooling(HookRunner.PREK))))
    (warning,) = [d for d in engine.diagnostics if d.severity is Severity.WARNING]
    assert "uv run prek install" in warning.message
    assert engine.completed_tasks == []


def test_no_action_runs_nothing(tmp_path, monkeypatch, mocker):
    engine, run = executor(tmp_path, monkeypatch, mocker)
    engine._apply_hooks(NO_HOOK_ACTION)
    run.assert_not_called()
    assert not Path(".git").exists()
