"""Auto-generated fallback hook revisions. Do not edit manually.

This file is automatically generated by scripts/sync_registry_fallbacks.py
prior to release. It ensures that the offline fallbacks shipped with the
CLI are up-to-date with the latest registry state.
"""

# Immutable fallback state guarantees zero downtime if the user is offline.
# Formatted as string keys to avoid circular imports.
DEFAULT_REVISIONS: dict[str, str] = {
    "https://github.com/pre-commit/pre-commit-hooks": "v6.0.0",
    "https://github.com/gitleaks/gitleaks": "v8.30.1",
    "https://github.com/DavidAnson/markdownlint-cli2": "v0.23.2",
    "https://github.com/commitizen-tools/commitizen": "v4.18.0",
    "https://github.com/renovatebot/pre-commit-hooks": "44.48.0",
}
