"""The git hooks a project's hook manager installs, kept in line by ``sync``.

Installed hooks live in ``.git/hooks``, outside the project's files, so they are
local to each clone: a fresh checkout has none, and they never make a project
out of date. ``init`` installs them as a post-install task. ``sync`` compares
the hooks on disk with the recipe and installs the missing ones, and removes
the ones a hook manager generated that can now only fail: those of a manager
the recipe switched away from, and every generated hook once the recipe wants
none and no hook configuration is left for them to run.

Planning only reads ``.git/hooks``; it never runs git.
"""

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .documents import pre_commit
from .manifest import SystemTask, ToolingManifest
from .workflows import HookRunner

HOOKS_DIR = Path(".git") / "hooks"
"""Where git looks for a repository's hooks, relative to the project root."""

_MARKERS = {
    HookRunner.PREK: "# File generated by prek",
    HookRunner.PRE_COMMIT: "# File generated by pre-commit",
}
"""The comment each manager writes near the top of every hook it generates."""

_HEADER_BYTES = 512


def install_task(tooling: ToolingManifest) -> SystemTask:
    """Returns the command that installs every hook the tooling wants.

    Args:
        tooling: The planned tooling, whose hook runner is set.
    """
    runner = tooling.hook_runner
    return SystemTask(
        ["uv", "run", runner.value, "install"],
        # `uv run` first builds the project environment when a fresh clone has
        # none, installing every dev dependency: as long as the resolver gets.
        timeout=600,
        description=f"Installing {runner.value} git hooks",
        # Every hook type is known only once all modules build, so each is owned.
        owned_files=[
            (HOOKS_DIR / kind).as_posix() for kind in sorted(wanted_hooks(tooling))
        ],
    )


def wanted_hooks(tooling: ToolingManifest) -> frozenset[str]:
    """Returns the hook types the tooling's runner installs, or none without one."""
    if not tooling.wants_hooks:
        return frozenset()
    return frozenset({"pre-commit", *tooling.pre_commit_install_hook_types})


def configurations() -> frozenset[str]:
    """Returns every file a hook manager can read its configuration from."""
    return frozenset(
        name
        for locations in pre_commit.LOCATIONS.values()
        for name in (locations.target, *locations.aliases, *locations.competitors)
    )


@dataclass(frozen=True)
class HookAction:
    """What ``sync`` does to a clone's installed hooks.

    Attributes:
        install: The command that installs the wanted hooks, when one is missing.
        remove: Generated hooks to delete, as POSIX paths from the project root.
    """

    install: SystemTask | None = None
    remove: tuple[str, ...] = ()

    @property
    def pending(self) -> bool:
        """Returns whether any hook changes."""
        return self.install is not None or bool(self.remove)

    def to_dict(self) -> dict[str, Any]:
        """Serializes the action with sorted POSIX paths."""
        return {
            "install": list(self.install.command) if self.install else None,
            "remove": sorted(self.remove),
        }


NO_HOOK_ACTION = HookAction()


def generator(hook: Path) -> HookRunner | None:
    """Returns the hook manager that generated a hook script, if one did.

    Args:
        hook: A file in the hooks directory.
    """
    try:
        with hook.open("rb") as handle:
            header = handle.read(_HEADER_BYTES).decode("utf-8", "replace")
    except OSError:
        return None
    return next(
        (runner for runner, marker in _MARKERS.items() if marker in header), None
    )


def plan_hooks(
    root: Path, tooling: ToolingManifest, configured: Iterable[str]
) -> HookAction:
    """Compares a clone's installed hooks with what the tooling wants.

    Nothing is planned outside a plain git repository: a worktree or submodule
    keeps its hooks elsewhere, which only git can say.

    Args:
        root: The project root.
        tooling: The planned tooling.
        configured: The hook configuration files that exist once the planned
            edits are applied.

    Returns:
        The hooks to install and remove.
    """
    hooks = root / HOOKS_DIR
    if not hooks.is_dir():
        return NO_HOOK_ACTION
    wanted = wanted_hooks(tooling)
    runner = tooling.hook_runner
    generated = {
        entry.name: made_by
        for entry in hooks.iterdir()
        if entry.is_file() and (made_by := generator(entry)) is not None
    }
    has_configuration = bool(set(configured) & configurations())
    remove = tuple(
        (HOOKS_DIR / name).as_posix()
        for name, made_by in sorted(generated.items())
        if _stale(made_by, runner, has_configuration)
    )
    missing = any(generated.get(kind) is not runner for kind in wanted)
    return HookAction(install_task(tooling) if missing else None, remove)


def _stale(made_by: HookRunner, runner: HookRunner, has_configuration: bool) -> bool:
    """Returns whether a generated hook can only fail.

    A hook the chosen runner generated keeps working, whatever its type. One
    another runner generated calls a runner the project no longer installs.
    Without a runner, a hook still works while the user keeps a configuration
    of their own.
    """
    if runner is HookRunner.NONE:
        return not has_configuration
    return made_by is not runner
