[project]
name = "demo-project"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "mpremote>=1.29.0",
    "pyserial>=3.5",
]
description = "Add your description here."
readme = "README.md"

[[project.authors]]
name = "your-name"
email = "your-email"
[dependency-groups]
dev = [
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["A", "B", "C4", "E", "F", "I", "RUF", "UP"]
ignore = ["E501"]
