"""Module exports for the Protostar manifest execution engine."""

from .base import (
    BootstrapModule,
    PathSignal,
    RequirementSignal,
    SectionSignal,
    Signal,
    TableSignal,
)
from .ci_layer import CIModule, ReleaseModule
from .lang_layer import LICENSE_MAP, PythonCore
from .system_layer import SystemWorkspaceModule
from .tooling_layer import (
    AGENTS_TARGET,
    AgentsModule,
    CodecovModule,
    CommitizenModule,
    DirenvModule,
    JustModule,
    MarkdownLintModule,
    MypyModule,
    PreCommitModule,
    PrekModule,
    PyreflyModule,
    PytestModule,
    ReadTheDocsModule,
    RenovateModule,
    RuffModule,
    RumdlModule,
    TyModule,
    ZensicalModule,
)

TOOLING_MODULES: tuple[BootstrapModule, ...] = (
    DirenvModule(),
    MarkdownLintModule(),
    RumdlModule(),
    RuffModule(),
    MypyModule(),
    TyModule(),
    PyreflyModule(),
    PytestModule(),
    PreCommitModule(),
    PrekModule(),
    CommitizenModule(),
    RenovateModule(),
    CodecovModule(),
    ZensicalModule(),
    ReadTheDocsModule(),
    CIModule(),
    ReleaseModule(),
    JustModule(),
    AgentsModule(),
)

__all__ = [
    "AGENTS_TARGET",
    "LICENSE_MAP",
    "TOOLING_MODULES",
    "AgentsModule",
    "BootstrapModule",
    "CIModule",
    "CodecovModule",
    "CommitizenModule",
    "DirenvModule",
    "JustModule",
    "MarkdownLintModule",
    "MypyModule",
    "PathSignal",
    "PreCommitModule",
    "PrekModule",
    "PyreflyModule",
    "PytestModule",
    "PythonCore",
    "ReadTheDocsModule",
    "ReleaseModule",
    "RenovateModule",
    "RequirementSignal",
    "RuffModule",
    "RumdlModule",
    "SectionSignal",
    "Signal",
    "SystemWorkspaceModule",
    "TableSignal",
    "TyModule",
    "ZensicalModule",
]
