#!/usr/bin/env python3
import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path

# Add src/ to sys.path to import the current fallbacks
sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src"))
)
from protostar._fallbacks import DEFAULT_REVISIONS

REGISTRY_URL = (
    "https://jacksonfergusondev.github.io/protostar-hook-registry/registry.json"
)
FALLBACKS_FILE = Path(__file__).parent.parent / "src" / "protostar" / "_fallbacks.py"


def generate_fallbacks_content(new_revisions: dict[str, str]) -> str:
    """Generate the python string content for _fallbacks.py."""
    lines = [
        '"""Auto-generated fallback hook revisions. Do not edit manually.',
        "",
        "This file is automatically generated by scripts/sync_registry_fallbacks.py",
        "prior to release. It ensures that the offline fallbacks shipped with the",
        "CLI are up-to-date with the latest registry state.",
        '"""',
        "",
        "# Immutable fallback state guarantees zero downtime if the user is offline.",
        "# Formatted as string keys to avoid circular imports.",
        "DEFAULT_REVISIONS: dict[str, str] = {",
    ]
    for url, rev in new_revisions.items():
        lines.append(f'    "{url}": "{rev}",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Main execution point for the sync script."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Only check, do not update"
    )
    args = parser.parse_args()

    print(f"Fetching latest registry from {REGISTRY_URL}...")
    try:
        with urllib.request.urlopen(REGISTRY_URL, timeout=5) as response:
            data = json.loads(response.read().decode("utf-8"))
    except Exception as e:
        print(f"Failed to fetch registry: {e}")
        sys.exit(1)

    if not isinstance(data, dict) or data.get("schema_version") != 1:
        print("Invalid registry schema.")
        sys.exit(1)

    remote_hooks = data.get("hooks", {})
    if not remote_hooks:
        print("Remote registry is empty.")
        sys.exit(1)

    # Compare
    is_out_of_date = False
    for hook, rev in remote_hooks.items():
        if hook not in DEFAULT_REVISIONS or DEFAULT_REVISIONS[hook] != rev:
            is_out_of_date = True
            break
    for hook in DEFAULT_REVISIONS:
        if hook not in remote_hooks:
            is_out_of_date = True
            break

    if not is_out_of_date:
        print("Fallbacks are perfectly up to date with the remote registry!")
        sys.exit(0)

    if args.check:
        print("ERROR: Fallbacks are out of date compared to the remote registry!")
        print(
            "Please run `uv run python scripts/sync_registry_fallbacks.py` to update them."
        )
        sys.exit(1)

    print("Fallbacks are out of date. Updating src/protostar/_fallbacks.py...")
    new_content = generate_fallbacks_content(remote_hooks)
    FALLBACKS_FILE.write_text(new_content)
    print("WARNING: Fallbacks have been updated.")
    print(
        "Please review the changes in src/protostar/_fallbacks.py and rerun your bump/release command."
    )
    sys.exit(1)


if __name__ == "__main__":
    main()
