#!/usr/bin/env python3
import argparse
import json
import sys

from protostar._fallbacks import DEFAULT_REVISIONS
from protostar.fs import atomic_write_text
from protostar.registry import RemoteHook
from scripts._common import SRC_DIR, OutputStyle, fetch_bytes, report

REGISTRY_URL = (
    "https://jacksonfergusondev.github.io/protostar-hook-registry/registry.json"
)
FALLBACKS_FILE = SRC_DIR / "protostar" / "_fallbacks.py"


def generate_fallbacks_content(new_revisions: dict[str, str]) -> str:
    """Generate the python string content for _fallbacks.py."""
    lines = [
        '"""Auto-generated fallback hook revisions. Do not edit manually.',
        "",
        "This file is automatically generated by scripts/sync_registry_fallbacks.py",
        "prior to release. It ensures that the offline fallbacks shipped with the",
        "CLI are up-to-date with the latest registry state.",
        '"""',
        "",
        "# Immutable fallback state guarantees zero downtime if the user is offline.",
        "# Formatted as string keys to avoid circular imports.",
        "DEFAULT_REVISIONS: dict[str, str] = {",
    ]
    for url, rev in sorted(new_revisions.items()):
        lines.append(f"    {json.dumps(url)}: {json.dumps(rev)},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Main execution point for the sync script."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Only check, do not update"
    )
    args = parser.parse_args()

    report(f"Fetching latest registry from {REGISTRY_URL}...", style=OutputStyle.DETAIL)
    raw = fetch_bytes(REGISTRY_URL, timeout=5)
    try:
        data = json.loads(raw.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        report(f"Invalid registry JSON: {e}", style=OutputStyle.ERROR, stderr=True)
        sys.exit(1)

    if not isinstance(data, dict) or data.get("schema_version") != 1:
        report("Invalid registry schema.", style=OutputStyle.ERROR, stderr=True)
        sys.exit(1)

    raw_remote_hooks = data.get("hooks")
    if not isinstance(raw_remote_hooks, dict):
        report("Invalid registry hooks mapping.", style=OutputStyle.ERROR, stderr=True)
        sys.exit(1)
    supported_hook_urls = {hook.value for hook in RemoteHook}
    missing = supported_hook_urls - raw_remote_hooks.keys()
    if missing:
        report(
            f"Remote registry is missing supported hooks: {', '.join(sorted(missing))}.",
            style=OutputStyle.ERROR,
            stderr=True,
        )
        sys.exit(1)
    invalid = [
        url
        for url in sorted(supported_hook_urls)
        if not isinstance(raw_remote_hooks[url], str)
        or not raw_remote_hooks[url].strip()
    ]
    if invalid:
        report(
            f"Remote registry has invalid revisions for: {', '.join(invalid)}.",
            style=OutputStyle.ERROR,
            stderr=True,
        )
        sys.exit(1)
    remote_hooks = {
        k: v for k, v in raw_remote_hooks.items() if k in supported_hook_urls
    }

    # Compare
    is_out_of_date = dict(remote_hooks) != dict(DEFAULT_REVISIONS)

    if not is_out_of_date:
        report("Fallbacks match the remote registry.", style=OutputStyle.DETAIL)
        sys.exit(0)

    if args.check:
        report(
            "Fallbacks are out of date compared to the remote registry.",
            style=OutputStyle.ERROR,
            stderr=True,
        )
        report(
            "Run `uv run python -m scripts.sync_registry_fallbacks` to update them.",
            style=OutputStyle.COMMAND,
            stderr=True,
        )
        sys.exit(1)

    new_content = generate_fallbacks_content(remote_hooks)
    atomic_write_text(FALLBACKS_FILE, new_content)
    report(
        "Updated src/protostar/_fallbacks.py. Review and commit the changes.",
        style=OutputStyle.WARNING,
    )


if __name__ == "__main__":
    main()
