#!/usr/bin/env python3
"""Vendors the pinned house-style release into docs/house/.

house-style (https://github.com/JacksonFergusonDev/house-style) holds the
tokens, fonts, components, and scripts jacksonferguson.me shares with its
project sites. The docs copy one tagged release at build time instead of
loading it from another origin, so the site changes only when HOUSE_STYLE_TAG
does and every published docs version keeps the look it was built with.

Usage:
    python scripts/sync_house_style.py          # rewrite docs/house/ from the tag
    python scripts/sync_house_style.py --check  # exit 1 if docs/house/ differs
"""

from __future__ import annotations

import argparse
import io
import sys
import tarfile
from pathlib import Path, PurePosixPath

_repo_root = Path(__file__).resolve().parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from scripts._common import DOCS_DIR, REPO_ROOT, OutputStyle, fetch_bytes, report

HOUSE_STYLE_TAG = "v1.4.0"
REPOSITORY = "https://github.com/JacksonFergusonDev/house-style"
ARCHIVE_URL = (
    "https://codeload.github.com/JacksonFergusonDev/house-style/tar.gz/refs/tags/{tag}"
)
VENDOR_DIR = DOCS_DIR / "house"

# A Markdown file under docs/ would build as a page, so these land as text.
_RENAMES = {
    "GUIDELINES.md": "GUIDELINES.txt",
    "fonts/README.md": "fonts/README.txt",
    "icons/README.md": "icons/README.txt",
}


def _vendored(path: PurePosixPath) -> bool:
    """Whether a file from the release belongs in the docs."""
    if str(path) == "LICENSE" or str(path) in _RENAMES:
        return True
    if path.parts[0] == "css":
        return path.suffix == ".css"
    if path.parts[0] == "js":
        return path.suffix == ".js"
    if path.parts[0] == "icons":
        return path.suffix == ".svg"
    return path.parts[0] == "fonts" and path.suffix in {".woff2", ".txt"}


def release_files(archive: bytes, tag: str) -> dict[str, bytes]:
    """Maps each vendored path, relative to docs/house/, to its bytes.

    Args:
        archive: The release's source tarball.
        tag: The tag the tarball was downloaded for.

    Returns:
        The files to vendor, including a notice naming the tag.
    """
    files: dict[str, bytes] = {}
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                continue
            path = PurePosixPath(*PurePosixPath(member.name).parts[1:])
            if not path.parts or not _vendored(path):
                continue
            extracted = tar.extractfile(member)
            if extracted is None:
                continue
            files[_RENAMES.get(str(path), str(path))] = extracted.read()
    files["README.txt"] = (
        f"house-style {tag}, from {REPOSITORY}.\n"
        "Generated by scripts/sync_house_style.py; change HOUSE_STYLE_TAG there "
        "and run `just sync-house-style` instead of editing these files.\n"
    ).encode()
    return files


def committed_files(directory: Path) -> dict[str, bytes]:
    """Maps each file under ``directory`` to its bytes."""
    if not directory.is_dir():
        return {}
    return {
        path.relative_to(directory).as_posix(): path.read_bytes()
        for path in sorted(directory.rglob("*"))
        if path.is_file()
    }


def write_files(directory: Path, files: dict[str, bytes]) -> None:
    """Makes ``directory`` hold exactly ``files``."""
    for stale in set(committed_files(directory)) - set(files):
        (directory / stale).unlink()
    for name, content in files.items():
        target = directory / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    for folder in sorted(directory.rglob("*"), reverse=True):
        if folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()


def main() -> None:
    """Vendors the pinned release, or checks that the vendored copy matches it."""
    parser = argparse.ArgumentParser(
        description="Vendor the pinned house-style release."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/house/ differs from the pinned release.",
    )
    args = parser.parse_args()

    files = release_files(
        fetch_bytes(ARCHIVE_URL.format(tag=HOUSE_STYLE_TAG)), HOUSE_STYLE_TAG
    )
    location = VENDOR_DIR.relative_to(REPO_ROOT)
    if args.check:
        if committed_files(VENDOR_DIR) != files:
            report(
                f"{location} differs from house-style {HOUSE_STYLE_TAG}. Run `just sync-house-style` and commit the result.",
                style=OutputStyle.ERROR,
                stderr=True,
            )
            sys.exit(1)
        report(
            f"{location} matches house-style {HOUSE_STYLE_TAG}.",
            style=OutputStyle.SUCCESS,
        )
        return

    write_files(VENDOR_DIR, files)
    report(
        f"Vendored house-style {HOUSE_STYLE_TAG} into {location}.",
        style=OutputStyle.SUCCESS,
    )


if __name__ == "__main__":
    main()
