[env]
active_presets = ["cli"]

# Tooling opinions for robust software engineering
ruff = true
direnv = true
mypy = true
pytest = true
pre_commit = true

# > [!WARNING]
# > Do not use `{{VAR}}` interpolation syntax inside template configs,
# > as it will trigger interactive prompts at load time before engine execution.
