[env]
active_presets = ["cli"]

# Tooling opinions for robust software engineering
ruff = true
direnv = true
mypy = true
pytest = true
pre_commit = true

[dev.pyproject]
strict_typing = '''
[tool.mypy]
strict = true
disallow_untyped_defs = true
'''
