# --- Dependencies ---
dependencies = ["torch", "scikit-learn", "huggingface_hub", "tqdm"]

# --- Directory Architecture ---
directories = ["models", "data", "notebooks", "src"]

# --- Version Control Ignores ---
vcs_ignores = [
    "*.pt",
    "*.pth",
    "*.safetensors",
    "*.onnx",
    "*.log",
    "wandb/",
    "mlruns/",
    "runs/",
    ".ipynb_checkpoints/",
]
