# --- Dependencies ---
dependencies = [
    "numpy",
    "matplotlib",
    "seaborn",
    "pandas",
    "scipy",
    "ipykernel",
    "scikit-learn",
]

# --- Directory Architecture ---
directories = ["data", "notebooks", "src"]

# --- Version Control Ignores ---
vcs_ignores = ["*.csv", "*.parquet", "*.nc", ".ipynb_checkpoints/"]
