name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.14"

      - name: Build distribution
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1

  sync-homebrew:
    name: Delegate Homebrew Update
    needs: build-n-publish
    uses: JacksonFergusonDev/ci-cd-tooling/.github/workflows/update-homebrew.yml@9bb493d0b0ee059aee4b89234bc9e6130857ec23 # main
    with:
      tag: ${{ github.ref_name }}
      package_name: "protostar"
      formula_path: "Formula/protostar.rb"
    secrets:
      TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
